version: '3'
services:
  lutris:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - lutris:/home/user:rw
    privileged: true
    network_mode: host
    environment:
      DISPLAY: $DISPLAY
volumes:
  lutris:
    external: false